### ISSUE TITLE
2022_v1 pystan test error under windows

### ISSUE THREAD

**Issue by WeiliangChenOIST** [CNS-OIST/ocnc#1]
The following error appears when running the test note book (pystan test block) https://github.com/CNS-OIST/ocnc/blob/main/simulator_tests.ipynb with the default `cnsoist/ocnc:2022_v1` image on windows 10 Pro.

```
Building...

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-7c5183bd17d1> in <module>
     25                 "y": [28,  8, -3,  7, -1,  1, 18, 12],
     26                 "sigma": [15, 10, 16, 11,  9, 11, 10, 18]}
---> 27 posterior = stan.build(schools_code, data=schools_data, random_seed=1)
     28 fit = posterior.sample(num_chains=4, num_samples=1000)
     29 eta = fit["eta"]  # array with shape (8, 4000)

/usr/local/lib/python3.8/dist-packages/stan/model.py in build(program_code, data, random_seed)
    515 
    516     try:
--> 517         return asyncio.run(go())
    518     except KeyboardInterrupt:
    519         return  # type: ignore

/usr/local/lib/python3.8/dist-packages/nest_asyncio.py in run(main, debug)
     33         task = asyncio.ensure_future(main)
     34         try:
---> 35             return loop.run_until_complete(task)
     36         finally:
     37             if not task.done():

/usr/local/lib/python3.8/dist-packages/nest_asyncio.py in run_until_complete(self, future)
     87                 raise RuntimeError(
     88                     'Event loop stopped before Future completed.')
---> 89             return f.result()
     90 
     91     def _run_once(self):

/usr/lib/python3.8/asyncio/futures.py in result(self)
    176         self.__log_traceback = False
    177         if self._exception is not None:
--> 178             raise self._exception
    179         return self._result
    180 

/usr/lib/python3.8/asyncio/tasks.py in __step(***failed resolving arguments***)
    278                 # We use the `send` method directly, because coroutines
    279                 # don't have `__iter__` and `__next__` methods.
--> 280                 result = coro.send(None)
    281             else:
    282                 result = coro.throw(exc)

/usr/local/lib/python3.8/dist-packages/stan/model.py in go()
    484                 match = re.search(r"""ValueError\(['"](.*)['"]\)""", resp.json()["message"])
    485                 if not match:  # unknown error, should not happen
--> 486                     raise RuntimeError(resp.json()["message"])
    487                 exception_body = match.group(1).encode().decode("unicode_escape")
    488                 error_type_match = re.match(r"(Semantic|Syntax) error", exception_body)

RuntimeError: Exception while building model extension module: `CompileError(DistutilsExecError("command 'x86_64-linux-gnu-gcc' failed with exit status 1"))`, traceback: `['  File "/usr/local/lib/python3.8/dist-packages/httpstan/views.py", line 114, in handle_create_model\n    compiler_output = await httpstan.models.build_services_extension_module(program_code)\n', '  File "/usr/local/lib/python3.8/dist-packages/httpstan/models.py", line 168, in build_services_extension_module\n    compiler_output = await asyncio.get_running_loop().run_in_executor(\n', '  File "/usr/lib/python3.8/asyncio/futures.py", line 260, in __await__\n    yield self  # This tells Task to wait for completion.\n', '  File "/usr/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup\n    future.result()\n', '  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result\n    raise self._exception\n', '  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\n', '  File "/usr/local/lib/python3.8/dist-packages/httpstan/build_ext.py", line 80, in run_build_ext\n    build_extension.run()\n', '  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run\n    self.build_extensions()\n', '  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions\n    self._build_extensions_serial()\n', '  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial\n    self.build_extension(ext)\n', '  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension\n    objects = self.compiler.compile(sources,\n', '  File "/usr/lib/python3.8/distutils/ccompiler.py", line 574, in compile\n    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)\n', '  File "/usr/lib/python3.8/distutils/unixccompiler.py", line 120, in _compile\n    raise CompileError(msg)\n']`


```

**Comment by WeiliangChenOIST** [comment]
This happens on a 32 core  threadripper machine where all 32 cores were all assigned as docker resource but with 2G of total memory assigned. Thus the above compilation from stan exhausted the memory, causing the error. 

Resolved by increasing the memory in docker setting.
